//! Renders `stacks.toml` into everything the stack actually runs on, laid out under the
//! `--data-dir`:
//!
//!   <data-dir>/rendered/   compose file + per-service configs (regenerated)
//!   <data-dir>/chainstate/ service state: chainstate, Postgres, signer db
//!
//! Service state is bind-mounted from `chainstate/` (not named Docker volumes) so the entire stack,
//! configs and data, lives where the operator said.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::Result;
use serde::Serialize;

use crate::config::{Deployment, ServiceMode};
use crate::utils::secrets;
use crate::utils::services::*;

pub use crate::config::DEFAULT_PROJECT;

/// Docker networks, split so a compromised API-side container cannot reach the signer (or bitcoind)
/// directly. Each service joins only the networks it needs; the node bridges all three because
/// everything talks to it.
const NET_BITCOIN: &str = "bitcoin"; // bitcoind + node
const NET_CORE: &str = "core"; // node + signer
const NET_SERVICES: &str = "services"; // api + mesh + postgres (+ node for RPC/events)

/// Path of the compose file within a data dir.
pub fn compose_file(data_dir: &Path) -> PathBuf {
    data_dir.join("rendered/docker-compose.yml")
}

const GENERATED_HEADER: &str = "# GENERATED by `stacksup config render` — edit stacks.toml instead; changes here will be overwritten.\n";

/// Events the stacks-api observer subscribes to (everywhere it is wired).
///
/// "*" delivers exactly /new_block (with all events unfiltered), /new_burn_block, /new_mempool_tx,
/// and /drop_mempool_tx — and does NOT include /stackerdb_chunks or /proposal_response (stacks-core
/// docs/event-dispatcher.md). Don't narrow it to ["stx", ...]: that filters /new_block's events to
/// STX-only, dropping the FT/NFT/contract events the API indexes. Invalid keys panic the node at
/// startup.
const API_EVENTS_KEYS: &str = r#"["*"]"#;

/// The Postgres database and schema the blockchain API owns. Fixed names: they only apply to the
/// managed Postgres (an external API brings its own database, and an external Postgres pairs with
/// an enabled API via these).
const API_PG_DATABASE: &str = "stacks_blockchain_api";
const API_PG_SCHEMA: &str = "stacks_blockchain_api";

#[derive(Serialize)]
struct ComposeFile {
    /// Compose project name, embedded so every `docker compose -f` invocation (ours or the
    /// operator's) lands on this deployment's containers and networks without a -p flag.
    name: String,
    services: BTreeMap<String, ComposeService>,
    networks: BTreeMap<String, Option<()>>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    volumes: BTreeMap<String, Option<()>>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    secrets: BTreeMap<String, ComposeSecret>,
}

#[derive(Serialize)]
struct ComposeSecret {
    file: String,
}

#[derive(Serialize, Default)]
struct ComposeService {
    image: String,
    container_name: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    entrypoint: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    command: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    ports: Vec<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    environment: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    env_file: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    volumes: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    depends_on: Vec<String>,
    restart: String,
    networks: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    secrets: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    extra_hosts: Vec<String>,
    // Hardening knobs (used by services whose upstream compose ships them).
    #[serde(skip_serializing_if = "Option::is_none")]
    init: Option<bool>,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    read_only: bool,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    tmpfs: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    security_opt: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    cap_drop: Vec<String>,
}

impl ComposeService {
    fn new(deployment: &Deployment, name: &str, image: &str) -> Self {
        let project = deployment.project();
        // The default project keeps the historical names (stacks-* bare, generic ones prefixed). A
        // named deployment prefixes everything — container names are a docker-wide namespace.
        let container_name = if project == DEFAULT_PROJECT {
            if name.starts_with("stacks-") {
                name.to_string()
            } else {
                format!("{project}-{name}")
            }
        } else {
            format!("{project}-{name}")
        };
        ComposeService {
            image: image.into(),
            container_name,
            restart: "unless-stopped".into(),
            // Every builder sets its own network membership (least access).
            networks: Vec::new(),
            // Lets managed services reach "external" services running on the operator's localhost,
            // a common setup that trips people up.
            extra_hosts: vec!["host.docker.internal:host-gateway".into()],
            ..Default::default()
        }
    }
}

pub fn render(deployment: &Deployment, data_dir: &Path) -> Result<PathBuf> {
    let dir = data_dir.join("rendered");
    std::fs::create_dir_all(&dir)?;

    let mut compose = ComposeFile {
        name: deployment.project().to_string(),
        services: BTreeMap::new(),
        networks: BTreeMap::new(),
        volumes: BTreeMap::new(),
        secrets: BTreeMap::new(),
    };

    // Pre-create bind-mount sources so docker doesn't create them root-owned.
    let chainstate_subdir = |name: &str| -> Result<()> {
        std::fs::create_dir_all(data_dir.join("chainstate").join(name))?;
        Ok(())
    };

    if deployment.bitcoind.mode == ServiceMode::Enabled {
        chainstate_subdir("bitcoind")?;
        compose
            .services
            .insert("bitcoind".into(), bitcoind_service(deployment));
    }

    if deployment.stacks_node.mode == ServiceMode::Enabled {
        chainstate_subdir("stacks-node")?;
        std::fs::create_dir_all(dir.join("stacks-node"))?;
        // Carries the bitcoind rpc password and node auth token -> 0600.
        secrets::write_0600(
            &dir.join("stacks-node/Config.toml"),
            &format!("{GENERATED_HEADER}{}", node_config_toml(deployment)),
        )?;
        compose
            .services
            .insert("stacks-node".into(), node_service(deployment));
    }

    if deployment.stacks_signer.mode == ServiceMode::Enabled {
        chainstate_subdir("stacks-signer")?;
        std::fs::create_dir_all(dir.join("stacks-signer"))?;
        // Carries the node auth token (auth_password) -> 0600.
        secrets::write_0600(
            &dir.join("stacks-signer/signer.toml"),
            &format!("{GENERATED_HEADER}{}", signer_config_toml(deployment)),
        )?;
        compose
            .services
            .insert("stacks-signer".into(), signer_service(deployment));
    }

    if deployment.stacks_api.mode == ServiceMode::Enabled {
        std::fs::create_dir_all(dir.join("stacks-api"))?;
        // Carries PG_PASSWORD and the node auth token -> 0600.
        secrets::write_0600(
            &dir.join("stacks-api/.env"),
            &format!("{GENERATED_HEADER}{}", api_env(deployment)),
        )?;
        compose
            .services
            .insert("stacks-api".into(), api_service(deployment));
    }

    if deployment.stacks_mesh_api.mode == ServiceMode::Enabled {
        std::fs::create_dir_all(dir.join("stacks-mesh-api"))?;
        // Carries the node auth token -> 0600.
        secrets::write_0600(
            &dir.join("stacks-mesh-api/.env"),
            &format!("{GENERATED_HEADER}{}", mesh_api_env(deployment)),
        )?;
        compose
            .services
            .insert("stacks-mesh-api".into(), mesh_api_service(deployment));
    }

    if deployment.signer_sidekick.mode == ServiceMode::Enabled {
        std::fs::create_dir_all(dir.join("signer-sidekick"))?;
        // Carries the dashboard auth token (and optionally a Hiro API key) -> 0600.
        secrets::write_0600(
            &dir.join("signer-sidekick/.env"),
            &format!("{GENERATED_HEADER}{}", sidekick_env(deployment)),
        )?;
        ensure_sidekick_profiles(deployment, data_dir, &dir.join("signer-sidekick"))?;
        // Sidekick runs as a non-root user (uid 10001), so its sqlite lives in a named volume
        // (auto-chowned by docker) instead of a chainstate/ bind mount, which the container
        // user could not write on Linux.
        compose.volumes.insert("sidekick-data".into(), None);
        compose
            .services
            .insert("signer-sidekick".into(), sidekick_service(deployment));
    }

    if deployment.postgres.mode == ServiceMode::Enabled {
        chainstate_subdir("postgres")?;
        std::fs::create_dir_all(data_dir.join("downloads"))?;
        std::fs::create_dir_all(dir.join("secrets"))?;
        secrets::write_0600(
            &dir.join("secrets/pg_password"),
            deployment.postgres.password.as_deref().unwrap_or_default(),
        )?;
        compose.secrets.insert(
            "pg_password".into(),
            ComposeSecret {
                file: "./secrets/pg_password".into(),
            },
        );
        compose
            .services
            .insert("postgres".into(), postgres_service(deployment));
    }

    // Declare exactly the networks the rendered services joined.
    for svc in compose.services.values() {
        for net in &svc.networks {
            compose.networks.entry(net.clone()).or_insert(None);
        }
    }

    let yaml = serde_yaml::to_string(&compose)?;
    std::fs::write(compose_file(data_dir), format!("{GENERATED_HEADER}{yaml}"))?;

    // Reversed (push) edges we can't wire ourselves: emit the node-side config.
    if deployment.stacks_node.mode == ServiceMode::External
        && let Some(snippet) = apply_to_your_node(deployment)
    {
        // Carries the node auth token -> 0600.
        secrets::write_0600(&dir.join("apply-to-your-node.toml"), &snippet)?;
    }

    Ok(dir)
}

fn bitcoind_service(deployment: &Deployment) -> ComposeService {
    let rpc = bitcoind_rpc_port(deployment);
    let p2p = bitcoind_p2p_port(deployment);
    let mut svc = ComposeService::new(deployment, "bitcoind", &bitcoind_image(deployment));
    svc.command = vec![
        "-server=1".into(),
        "-txindex=0".into(),
        format!("-chain={}", deployment.net.bitcoind.chain),
        "-rpcbind=0.0.0.0".into(),
        "-rpcallowip=0.0.0.0/0".into(),
        // A salted hash, unlike -rpcpassword, safe to expose via docker inspect. The plaintext
        // lives in secrets.toml and the node's mounted Config.toml only. The `$` separating salt
        // from digest must be `$$` in the compose file or interpolation swallows the digest.
        format!(
            "-rpcauth={}",
            secrets::bitcoind_rpcauth(
                deployment.bitcoind.rpc_user.as_deref().unwrap_or_default(),
                deployment
                    .bitcoind
                    .rpc_password
                    .as_deref()
                    .unwrap_or_default(),
            )
            .replace('$', "$$")
        ),
    ];
    // Loopback-bind the RPC port: every container carries a host.docker.internal alias, so a
    // 0.0.0.0 publish would let API-side containers reach bitcoind through the host, bypassing the
    // network split. Operators still get bitcoin-cli on localhost. Only an external node (running
    // off-host) needs the wide binding. P2P stays open, it exists to accept peers.
    let rpc_publish = if deployment.stacks_node.mode == ServiceMode::External {
        format!("{}:{rpc}", deployment.published(rpc))
    } else {
        format!("127.0.0.1:{}:{rpc}", deployment.published(rpc))
    };
    svc.ports = vec![rpc_publish, format!("{}:{p2p}", deployment.published(p2p))];
    svc.volumes = vec!["../chainstate/bitcoind:/home/bitcoin/.bitcoin".into()];
    svc.networks = vec![NET_BITCOIN.into()];
    svc
}

fn node_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new(deployment, "stacks-node", &stacks_node_image(deployment));
    svc.command = vec![
        "stacks-node".into(),
        "start".into(),
        "--config".into(),
        "/etc/stacks/Config.toml".into(),
    ];
    svc.ports = vec![
        format!("{}:{NODE_RPC_PORT}", deployment.published(NODE_RPC_PORT)),
        format!("{}:{NODE_P2P_PORT}", deployment.published(NODE_P2P_PORT)),
    ];
    svc.volumes = vec![
        "./stacks-node/Config.toml:/etc/stacks/Config.toml:ro".into(),
        "../chainstate/stacks-node:/stacks-blockchain".into(),
    ];
    if deployment.bitcoind.mode == ServiceMode::Enabled {
        svc.depends_on.push("bitcoind".into());
    }
    // The node pushes events to the API; if the API is down at boot the node retries, but starting
    // after the API avoids stalling block processing.
    if deployment.stacks_api.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-api".into());
    }
    // Always on `core` (its home even with no signer); `bitcoin` only with a managed bitcoind;
    // `services` only when an API-side consumer needs its RPC or receives its event pushes.
    svc.networks = vec![NET_CORE.into()];
    if deployment.bitcoind.mode == ServiceMode::Enabled {
        svc.networks.insert(0, NET_BITCOIN.into());
    }
    if deployment.stacks_api.mode == ServiceMode::Enabled
        || deployment.stacks_mesh_api.mode == ServiceMode::Enabled
    {
        svc.networks.push(NET_SERVICES.into());
    }
    svc
}

fn signer_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new(
        deployment,
        "stacks-signer",
        &stacks_signer_image(deployment),
    );
    svc.command = vec![
        "stacks-signer".into(),
        "run".into(),
        "-c".into(),
        "/etc/stacks/signer.toml".into(),
    ];
    svc.volumes = vec![
        "./stacks-signer/signer.toml:/etc/stacks/signer.toml:ro".into(),
        "../chainstate/stacks-signer:/var/lib/stacks-signer".into(),
    ];
    if deployment.stacks_node.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-node".into());
    }
    svc.networks = vec![NET_CORE.into()];
    svc
}

fn api_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new(deployment, "stacks-api", &stacks_api_image(deployment));
    svc.ports = vec![format!("{}:{API_PORT}", deployment.published(API_PORT))];
    svc.env_file = vec!["./stacks-api/.env".into()];
    if deployment.postgres.mode == ServiceMode::Enabled {
        svc.depends_on.push("postgres".into());
    }
    svc.networks = vec![NET_SERVICES.into()];
    svc
}

fn mesh_api_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new(
        deployment,
        "stacks-mesh-api",
        &stacks_mesh_api_image(deployment),
    );
    svc.ports = vec![format!(
        "{}:{MESH_API_PORT}",
        deployment.published(MESH_API_PORT)
    )];
    svc.env_file = vec!["./stacks-mesh-api/.env".into()];
    if deployment.stacks_node.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-node".into());
    }
    svc.networks = vec![NET_SERVICES.into()];
    svc
}

/// Postgres major from the configured version tag: "17" -> 17, "17.5-alpine" -> 17, "latest"/absent
/// -> None.
fn postgres_major(deployment: &Deployment) -> Option<u32> {
    deployment
        .postgres
        .version
        .as_deref()?
        .split(['.', '-'])
        .next()?
        .parse()
        .ok()
}

fn postgres_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new(deployment, "postgres", &postgres_image(deployment));
    svc.ports = vec![format!(
        "{}:{POSTGRES_PORT}",
        deployment.published(POSTGRES_PORT)
    )];
    svc.networks = vec![NET_SERVICES.into()];
    svc.environment.insert(
        "POSTGRES_USER".into(),
        deployment
            .postgres
            .user
            .clone()
            .unwrap_or_else(|| "postgres".into()),
    );
    // Password arrives via a compose secret file, not container env, `docker inspect` shows only
    // the path.
    svc.environment.insert(
        "POSTGRES_PASSWORD_FILE".into(),
        "/run/secrets/pg_password".into(),
    );
    svc.secrets = vec!["pg_password".into()];
    svc.environment
        .insert("POSTGRES_DB".into(), API_PG_DATABASE.into());
    // Postgres 18+ images keep data in a version-specific subdirectory and require the mount at
    // /var/lib/postgresql (enabling pg_upgrade across majors); images <= 17 use
    // PGDATA=/var/lib/postgresql/data and need the mount there. Unknown majors (e.g. `latest`) get
    // the 18+ convention.
    let data_target = match postgres_major(deployment) {
        Some(major) if major <= 17 => "/var/lib/postgresql/data",
        _ => "/var/lib/postgresql",
    };
    svc.volumes = vec![
        format!("../chainstate/postgres:{data_target}"),
        // Read-only view of downloaded archives so pg_restore (which needs a seekable file, not
        // stdin) can restore dumps fetched by `stacksup chainstate download`.
        "../downloads:/downloads:ro".into(),
    ];

    // Ensure the API's schema exists on EVERY boot, not just first init,
    // /docker-entrypoint-initdb.d only runs on an empty data directory. The schema creator runs as
    // a background job while postgres is exec'd as PID 1, so SIGTERM from `stacksup stop` reaches
    // postgres directly and shutdown is clean (a backgrounded postgres under bash would be
    // SIGKILLed after the grace period instead).
    let user = deployment
        .postgres
        .user
        .clone()
        .unwrap_or_else(|| "postgres".into());
    let db = API_PG_DATABASE;
    svc.entrypoint = vec![
        "/bin/bash".into(),
        "-c".into(),
        format!(
            "(until pg_isready -U {user} -d {db}; do sleep 3; done && \
             psql -U {user} -d {db} -c 'CREATE SCHEMA IF NOT EXISTS {API_PG_SCHEMA};' || true) & \
             exec docker-entrypoint.sh postgres"
        ),
    ];
    svc
}

/// The stacks-node Config.toml. Cross-service values (bitcoind endpoint, event observers, signer
/// auth) are derived from the same `Deployment` the other configs come from, matched by
/// construction. The testnet shape mirrors stacks-core's sample/conf/testnet-follower-conf.toml.
fn node_config_toml(deployment: &Deployment) -> String {
    let net = &deployment.net;
    let mut out = String::new();

    out.push_str("[node]\n");
    out.push_str("working_dir = \"/stacks-blockchain\"\n");
    out.push_str(&format!("rpc_bind = \"0.0.0.0:{NODE_RPC_PORT}\"\n"));
    out.push_str(&format!("p2p_bind = \"0.0.0.0:{NODE_P2P_PORT}\"\n"));
    if let Some(bootstrap) = &net.node.bootstrap_node {
        out.push_str(&format!("bootstrap_node = \"{bootstrap}\"\n"));
    }
    if deployment.stacks_signer.mode != ServiceMode::Disabled {
        out.push_str("stacker = true\n");
    } else {
        out.push_str("miner = false\nstacker = false\n");
    }
    if deployment.signer_sidekick.mode == ServiceMode::Enabled {
        // Sidekick's Signer Health page reads node telemetry (container-internal endpoint).
        out.push_str(&format!(
            "prometheus_bind = \"0.0.0.0:{NODE_METRICS_PORT}\"\n"
        ));
    }
    if let Some(extra) = &net.node.node_extra {
        out.push_str(extra.trim());
        out.push('\n');
    }
    out.push('\n');

    out.push_str("[connection_options]\n");
    out.push_str(&format!(
        "auth_token = \"{}\"\n",
        node_auth_token(deployment)
    ));
    out.push_str("private_neighbors = false\n\n");

    out.push_str("[burnchain]\n");
    out.push_str(&format!(
        "mode = \"{}\"\nchain = \"bitcoin\"\n",
        net.node.burnchain_mode
    ));
    // Burnchain endpoint: managed/external bitcoind, else the network's hosted default (validation
    // guarantees one of these exists for a node).
    if let Some(host) = bitcoind_host(deployment).or_else(|| net.bitcoind.default_host.clone()) {
        out.push_str(&format!("peer_host = \"{host}\"\n"));
        out.push_str(&format!(
            "rpc_port = {}\npeer_port = {}\n",
            bitcoind_rpc_port(deployment),
            bitcoind_p2p_port(deployment)
        ));
        // Credentials: our managed bitcoind always has them (tool defaults); an external one only
        // when both are explicitly configured, validation rejects partial credentials, so no
        // silent fallbacks.
        if deployment.bitcoind.mode == ServiceMode::Enabled {
            out.push_str(&format!(
                "username = \"{}\"\npassword = \"{}\"\n",
                deployment.bitcoind.rpc_user.as_deref().unwrap_or_default(),
                deployment
                    .bitcoind
                    .rpc_password
                    .as_deref()
                    .unwrap_or_default(),
            ));
        } else if let (Some(user), Some(password)) = (
            &deployment.bitcoind.rpc_user,
            &deployment.bitcoind.rpc_password,
        ) {
            out.push_str(&format!(
                "username = \"{user}\"\npassword = \"{password}\"\n"
            ));
        }
    }
    if let (Some(prepare), Some(reward)) = (net.node.pox_prepare_length, net.node.pox_reward_length)
    {
        out.push_str(&format!(
            "pox_prepare_length = {prepare}\npox_reward_length = {reward}\n"
        ));
    }
    out.push('\n');

    if deployment.stacks_api.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[[events_observer]]\nendpoint = \"stacks-api:{API_EVENT_PORT}\"\nevents_keys = {API_EVENTS_KEYS}\ntimeout_ms = 300_000\n\n"
        ));
    } else if deployment.stacks_api.mode == ServiceMode::External
        && let (Some(host), Some(port)) = (
            &deployment.stacks_api.event_host,
            deployment.stacks_api.event_port,
        )
    {
        out.push_str(&format!(
                "[[events_observer]]\nendpoint = \"{host}:{port}\"\nevents_keys = {API_EVENTS_KEYS}\ntimeout_ms = 300_000\n\n"
            ));
    }

    if deployment.stacks_signer.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[[events_observer]]\nendpoint = \"stacks-signer:{SIGNER_ENDPOINT_PORT}\"\nevents_keys = [\"stackerdb\", \"block_proposal\", \"burn_blocks\"]\n\n"
        ));
    }

    for balance in &net.ustx_balances {
        out.push_str(&format!(
            "[[ustx_balance]]\naddress = \"{}\"\namount = {}\n\n",
            balance.address, balance.amount
        ));
    }
    for epoch in &net.epochs {
        out.push_str(&format!(
            "[[burnchain.epochs]]\nepoch_name = \"{}\"\nstart_height = {}\n\n",
            epoch.epoch_name, epoch.start_height
        ));
    }

    out
}

fn signer_config_toml(deployment: &Deployment) -> String {
    let node_host = node_rpc_host(deployment).unwrap_or_default();
    let metrics = if deployment.signer_sidekick.mode == ServiceMode::Enabled {
        // Sidekick reads /info, /heartbeat, /metrics from here (container-internal).
        format!("metrics_endpoint = \"0.0.0.0:{SIGNER_METRICS_PORT}\"\n")
    } else {
        String::new()
    };
    format!(
        r#"node_host = "{node_host}:{rpc_port}"
endpoint = "0.0.0.0:{endpoint_port}"
auth_password = "{auth}"
network = "{network}"
db_path = "/var/lib/stacks-signer/signerdb.sqlite"
{metrics}# TODO(hackathon): source the signing key from a secrets file, never this rendered config
stacks_private_key = "REPLACE_ME"
"#,
        rpc_port = node_rpc_port(deployment),
        endpoint_port = SIGNER_ENDPOINT_PORT,
        auth = node_auth_token(deployment),
        network = deployment.network,
    )
}

/// The node's `connection_options.auth_token`, which the signer's `auth_password` must match.
/// External nodes bring their own token (`[stacks-node] auth_token`); managed nodes use a
/// tool-managed one. The auth token shared by node config, signer, and mesh env, a single
/// deployment field, populated from secrets.toml (required by validation whenever something
/// consumes it).
fn node_auth_token(deployment: &Deployment) -> String {
    deployment
        .stacks_node
        .auth_token
        .clone()
        .unwrap_or_default()
}

fn api_env(deployment: &Deployment) -> String {
    let chain_id = format!("0x{:08x}", deployment.net.chain_id);
    let node_host = node_rpc_host(deployment).unwrap_or_default();
    let pg_host = postgres_host(deployment).unwrap_or_default();
    format!(
        r#"NODE_ENV=production
STACKS_CHAIN_ID={chain_id}
STACKS_BLOCKCHAIN_API_HOST=0.0.0.0
STACKS_BLOCKCHAIN_API_PORT={api_port}
STACKS_CORE_EVENT_HOST=0.0.0.0
STACKS_CORE_EVENT_PORT={event_port}
STACKS_CORE_RPC_HOST={node_host}
STACKS_CORE_RPC_PORT={node_rpc}
PG_HOST={pg_host}
PG_PORT={pg_port}
PG_USER={pg_user}
PG_PASSWORD={pg_password}
PG_DATABASE={pg_db}
PG_SCHEMA={pg_schema}
STACKS_API_STORE_RAW_EVENTS=false
TESTNET_BTC_FAUCET_ENABLED=false
TESTNET_STX_FAUCET_ENABLED=false
TESTNET_SBTC_FAUCET_ENABLED=false
"#,
        api_port = API_PORT,
        event_port = API_EVENT_PORT,
        node_rpc = node_rpc_port(deployment),
        pg_port = postgres_port(deployment),
        pg_schema = API_PG_SCHEMA,
        pg_user = deployment.postgres.user.as_deref().unwrap_or("postgres"),
        pg_password = deployment.postgres.password.as_deref().unwrap_or_default(),
        pg_db = API_PG_DATABASE,
    )
}

/// Env for the Stacks Mesh API (packages/api/src/env.ts is the schema of record). Online mode needs
/// the node's RPC endpoint and critically the node's `connection_options.auth_token`, which
/// this render guarantees matches by deriving both from the same source. Cache sizes/TTLs and
/// BLOCK_HASH_MODE are left to the service's own defaults.
fn mesh_api_env(deployment: &Deployment) -> String {
    let node_host = node_rpc_host(deployment).unwrap_or_default();
    format!(
        r#"API_HOST=0.0.0.0
API_PORT={api_port}
MODE=online
STACKS_CORE_RPC_SCHEME=http
STACKS_CORE_RPC_HOST={node_host}
STACKS_CORE_RPC_PORT={node_rpc}
STACKS_CORE_RPC_AUTH_TOKEN={auth_token}
"#,
        api_port = MESH_API_PORT,
        node_rpc = node_rpc_port(deployment),
        auth_token = node_auth_token(deployment),
    )
}

/// Env for signer-sidekick (compose.yaml in stx-labs/signer-sidekick is the schema of record).
/// The engine defaults to observe; operator-run is a deliberate operator opt-in, and its gas
/// wallet is generated inside sidekick's own UI — no key ever passes through here.
fn sidekick_env(deployment: &Deployment) -> String {
    let sk = &deployment.signer_sidekick;
    let mut out = format!(
        "SIDEKICK_NETWORK={network}\n\
         STACKS_NODE_RPC_URL=http://{node_host}:{node_rpc}\n\
         STACKS_API_URL={api_url}\n\
         SIDEKICK_MANAGER_PRINCIPAL={manager}\n\
         SIDEKICK_AUTH_TOKEN={auth}\n\
         SIDEKICK_ENGINE_MODE={engine}\n\
         SIDEKICK_TRUSTED_MANAGER_PROFILES_DIR=/etc/sidekick/trusted-managers\n\
         SIDEKICK_COMPATIBILITY_PROFILES_DIR=/etc/sidekick/network-compatibility\n",
        network = deployment.network,
        node_host = node_rpc_host(deployment).unwrap_or_default(),
        node_rpc = node_rpc_port(deployment),
        api_url = sidekick_api_url(deployment),
        manager = sk.manager_principal.as_deref().unwrap_or_default(),
        auth = sk.auth_token.as_deref().unwrap_or_default(),
        engine = sk.engine_mode.as_deref().unwrap_or("observe"),
    );
    if let Some(key) = sk.stacks_api_key.as_deref() {
        out.push_str(&format!("STACKS_API_KEY={key}\n"));
    }
    // Direct telemetry for the Signer Health page — only endpoints we render ourselves.
    if deployment.stacks_node.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "STACKS_NODE_METRICS_URL=http://stacks-node:{NODE_METRICS_PORT}/metrics\n"
        ));
    }
    if deployment.stacks_signer.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "STACKS_SIGNER_MONITORING_URL=http://stacks-signer:{SIGNER_METRICS_PORT}\n"
        ));
    }
    out
}

/// The indexed Stacks API sidekick reads roster/history from: explicit config wins, then the
/// deployment's own API, then the network's Hiro API.
fn sidekick_api_url(deployment: &Deployment) -> String {
    if let Some(url) = deployment.signer_sidekick.stacks_api_url.as_deref() {
        return url.to_string();
    }
    if deployment.stacks_api.mode == ServiceMode::Enabled {
        return format!("http://stacks-api:{API_PORT}");
    }
    deployment.net.hiro_api_url.clone().unwrap_or_default()
}

fn sidekick_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new(
        deployment,
        "signer-sidekick",
        &signer_sidekick_image(deployment),
    );
    svc.env_file = vec!["./signer-sidekick/.env".into()];
    // Dashboard only; bearer-token login is the only auth, so loopback-only. The event listener
    // (3700) stays container-internal.
    svc.ports = vec![format!(
        "127.0.0.1:{}:{SIDEKICK_CONTAINER_PORT}",
        deployment.published(SIDEKICK_PORT)
    )];
    svc.volumes = vec![
        "sidekick-data:/data".into(),
        "./signer-sidekick/trusted-managers:/etc/sidekick/trusted-managers:ro".into(),
        "./signer-sidekick/network-compatibility:/etc/sidekick/network-compatibility:ro".into(),
    ];
    // It talks to the node RPC and signer monitoring (core); joins services only to reach a
    // managed stacks-api when that is its indexed API.
    svc.networks = vec![NET_CORE.into()];
    if deployment.stacks_api.mode == ServiceMode::Enabled
        && deployment.signer_sidekick.stacks_api_url.is_none()
    {
        svc.networks.push(NET_SERVICES.into());
    }
    if deployment.stacks_node.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-node".into());
    }
    if deployment.stacks_signer.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-signer".into());
    }
    // Upstream compose hardening, minus its journald logging (which would break
    // `stacksup logs`).
    svc.init = Some(true);
    svc.read_only = true;
    svc.tmpfs = vec!["/tmp:size=64m,mode=1777".into()];
    svc.security_opt = vec!["no-new-privileges:true".into()];
    svc.cap_drop = vec!["ALL".into()];
    svc
}

/// The release image does not bundle sidekick's manager/compatibility profile directories (its
/// own deployment flow clones the repo at the release tag). Fetch them once per version from the
/// tag's tarball into rendered/signer-sidekick/, or accept user-provided directories as-is.
fn ensure_sidekick_profiles(deployment: &Deployment, data_dir: &Path, dest: &Path) -> Result<()> {
    let tag = crate::utils::versions::image_tag(&signer_sidekick_image(deployment));
    let marker = dest.join(".profiles-version");
    let have_dirs =
        dest.join("trusted-managers").is_dir() && dest.join("network-compatibility").is_dir();
    if have_dirs
        && std::fs::read_to_string(&marker)
            .map(|v| v.trim() == tag)
            .unwrap_or(false)
    {
        return Ok(());
    }
    if have_dirs && !marker.exists() {
        // User-provided profiles: theirs to manage, never overwritten.
        return Ok(());
    }

    let url =
        format!("https://codeload.github.com/stx-labs/signer-sidekick/tar.gz/refs/tags/{tag}");
    println!("Fetching signer-sidekick {tag} manager/compatibility profiles...");
    let resp = ureq::get(&url).call().map_err(|e| {
        anyhow::anyhow!(
            "cannot download sidekick profiles for {tag} ({e}) — offline, or the tag has no \
             GitHub release; place `trusted-managers/` and `network-compatibility/` from the \
             signer-sidekick repo under {} yourself",
            dest.display()
        )
    })?;
    let mut archive = tar::Archive::new(flate2::read::GzDecoder::new(resp.into_reader()));
    let staging = data_dir.join("downloads").join("sidekick-profiles-tmp");
    let _ = std::fs::remove_dir_all(&staging);
    std::fs::create_dir_all(&staging)?;
    for entry in archive.entries()? {
        let mut entry = entry?;
        let path = entry.path()?.into_owned();
        // Entries are prefixed "signer-sidekick-<ver>/"; keep only the two profile trees.
        let Ok(rel) = path.strip_prefix(path.components().next().unwrap()) else {
            continue;
        };
        let rel = rel.to_path_buf();
        if rel.starts_with("trusted-managers") || rel.starts_with("network-compatibility") {
            entry.unpack(staging.join(&rel))?;
        }
    }
    for sub in ["trusted-managers", "network-compatibility"] {
        if !staging.join(sub).is_dir() {
            anyhow::bail!("sidekick tarball for {tag} did not contain {sub}/");
        }
        let target = dest.join(sub);
        let _ = std::fs::remove_dir_all(&target);
        std::fs::rename(staging.join(sub), &target)?;
    }
    let _ = std::fs::remove_dir_all(&staging);
    std::fs::write(&marker, format!("{tag}\n"))?;
    Ok(())
}

/// Config the user must apply to their *external* node so push edges (events to the API, signer
/// wiring) actually close.
fn apply_to_your_node(deployment: &Deployment) -> Option<String> {
    let mut out = String::from(
        "# Add these blocks to your stacks-node config, then restart it.\n\
         # Verify events are flowing afterwards with `stacksup config check`.\n\n",
    );
    let mut needed = false;

    if deployment.stacks_api.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[[events_observer]]\nendpoint = \"<this-machine>:{API_EVENT_PORT}\"\nevents_keys = {API_EVENTS_KEYS}\n\n"
        ));
        needed = true;
    }
    if deployment.stacks_signer.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[node]\nstacker = true\n\n\
             [connection_options]\nauth_token = \"{}\"\n\n\
             [[events_observer]]\nendpoint = \"<this-machine>:{SIGNER_ENDPOINT_PORT}\"\nevents_keys = [\"stackerdb\", \"block_proposal\", \"burn_blocks\"]\n\n",
            node_auth_token(deployment)
        ));
        needed = true;
    }

    needed.then_some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Parse and merge the same test secrets `load()` would pull from a secrets.toml, so generators
    /// see a post-merge deployment. Managed bitcoind gets credentials; external keeps whatever the
    /// toml set.
    fn deployment(toml_str: &str) -> Deployment {
        let mut d = crate::config::test_deployment(toml_str);
        d.postgres
            .password
            .get_or_insert_with(|| "test-pg-password".into());
        d.stacks_node
            .auth_token
            .get_or_insert_with(|| "test-node-token".into());
        if d.bitcoind.mode == ServiceMode::Enabled {
            d.bitcoind.rpc_user.get_or_insert_with(|| "stacksup".into());
            d.bitcoind
                .rpc_password
                .get_or_insert_with(|| "test-btc-password".into());
        }
        d
    }

    const TESTNET_FULL: &str = "network = \"testnet\"\n[stacks-node]\nmode = \"enabled\"\nrole = \"signer-host\"\n[stacks-signer]\nmode = \"enabled\"\n[stacks-api]\nmode = \"enabled\"\n[stacks-mesh-api]\nmode = \"enabled\"\n[postgres]\nmode = \"enabled\"";

    #[test]
    fn testnet_node_config_matches_reference_shape() {
        let s = deployment("network = \"testnet\"\n[stacks-node]\nmode = \"enabled\"");
        let toml_text = node_config_toml(&s);
        let parsed: toml::Value =
            toml::from_str(&toml_text).expect("rendered node config is valid TOML");
        assert_eq!(parsed["burnchain"]["mode"].as_str(), Some("krypton"));
        assert_eq!(
            parsed["burnchain"]["peer_host"].as_str(),
            Some("bitcoin.regtest.hiro.so")
        );
        assert_eq!(parsed["burnchain"]["rpc_port"].as_integer(), Some(18443));
        assert!(
            parsed["node"]["bootstrap_node"]
                .as_str()
                .unwrap()
                .contains("seed.testnet.hiro.so")
        );
        // follower: explicitly not mining or stacking
        assert_eq!(parsed["node"]["miner"].as_bool(), Some(false));
        assert_eq!(parsed["node"]["stacker"].as_bool(), Some(false));
        assert_eq!(parsed["ustx_balance"].as_array().unwrap().len(), 12);
        assert_eq!(parsed["burnchain"]["epochs"].as_array().unwrap().len(), 14);
    }

    #[test]
    fn signer_flips_stacker_and_shares_auth_token() {
        let s = deployment(TESTNET_FULL);
        let node: toml::Value = toml::from_str(&node_config_toml(&s)).unwrap();
        assert_eq!(node["node"]["stacker"].as_bool(), Some(true));
        let token = node["connection_options"]["auth_token"]
            .as_str()
            .unwrap()
            .to_string();
        // signer auth_password and mesh env token must match the node's token
        assert!(signer_config_toml(&s).contains(&format!("auth_password = \"{token}\"")));
        assert!(mesh_api_env(&s).contains(&format!("STACKS_CORE_RPC_AUTH_TOKEN={token}")));
    }

    #[test]
    fn api_env_wires_postgres_and_schema() {
        let s = deployment(TESTNET_FULL);
        let env = api_env(&s);
        assert!(env.contains("PG_HOST=postgres"));
        assert!(env.contains(&format!("PG_DATABASE={API_PG_DATABASE}")));
        assert!(env.contains(&format!("PG_SCHEMA={API_PG_SCHEMA}")));
        assert!(env.contains("STACKS_CHAIN_ID=0x80000000"));
    }

    #[test]
    fn postgres_mount_depends_on_major() {
        let pg17 =
            deployment("network = \"testnet\"\n[postgres]\nmode = \"enabled\"\nversion = \"17\"");
        assert_eq!(postgres_major(&pg17), Some(17));
        assert!(postgres_service(&pg17).volumes[0].ends_with(":/var/lib/postgresql/data"));
        let latest = deployment("network = \"testnet\"\n[postgres]\nmode = \"enabled\"");
        assert_eq!(postgres_major(&latest), None);
        assert!(postgres_service(&latest).volumes[0].ends_with(":/var/lib/postgresql"));
        assert_eq!(
            postgres_major(&deployment(
                "network = \"testnet\"\n[postgres]\nversion = \"17.5-alpine\""
            )),
            Some(17)
        );
    }

    #[test]
    fn external_bitcoind_credentials_all_or_nothing() {
        // both set -> rendered verbatim
        let d = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"external\"\nhost = \"h\"\nrpc_user = \"u\"\nrpc_password = \"p\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let cfg = node_config_toml(&d);
        assert!(cfg.contains("username = \"u\"") && cfg.contains("password = \"p\""));
        // none set -> no credential lines, no silent defaults
        let d = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"external\"\nhost = \"h\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let cfg = node_config_toml(&d);
        assert!(!cfg.contains("username"));
        // managed -> generated secrets, never hardcoded defaults
        let d = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let cfg = node_config_toml(&d);
        assert!(cfg.contains("username = \"stacksup\""));
        assert!(cfg.contains("password = \"test-btc-password\""));
    }

    #[test]
    fn bitcoind_rpc_port_is_loopback_unless_node_is_external() {
        // managed node talks over the docker network; the host publish is
        // diagnostic only -> loopback (blocks the host.docker.internal bypass)
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let ports = bitcoind_service(&s).ports;
        assert!(ports[0].starts_with("127.0.0.1:"), "got: {ports:?}");
        assert!(!ports[1].starts_with("127.0.0.1:"), "p2p must accept peers");

        // an off-host node needs the wide binding
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"external\"\nrpc_host = \"h\"",
        );
        assert!(!bitcoind_service(&s).ports[0].starts_with("127.0.0.1:"));
    }

    #[test]
    fn bitcoind_rpcauth_dollar_is_escaped_for_compose() {
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let rpcauth = bitcoind_service(&s)
            .command
            .iter()
            .find(|a| a.starts_with("-rpcauth="))
            .unwrap()
            .clone();
        // `$$` survives compose interpolation as a literal `$`; a bare `$`
        // would swallow the digest ("variable is not set" -> blank).
        assert!(rpcauth.contains("$$"), "got: {rpcauth}");
        assert!(!rpcauth.replace("$$", "").contains('$'));
    }

    #[test]
    fn named_deployment_prefixes_and_shifts_only_host_ports() {
        let toml = "name = \"testnet-b\"\nport_offset = 100\nnetwork = \"testnet\"\n[stacks-node]\nmode = \"enabled\"\nrole = \"signer-host\"\n[stacks-signer]\nmode = \"enabled\"\n[stacks-api]\nmode = \"enabled\"\n[postgres]\nmode = \"enabled\"";
        let s = deployment(toml);
        // container names get the project prefix — a docker-wide namespace
        assert_eq!(node_service(&s).container_name, "testnet-b-stacks-node");
        assert_eq!(postgres_service(&s).container_name, "testnet-b-postgres");
        // host side shifts, container side doesn't
        assert_eq!(node_service(&s).ports, vec!["20543:20443", "20544:20444"]);
        assert_eq!(api_service(&s).ports, vec!["4099:3999"]);
        assert_eq!(postgres_service(&s).ports, vec!["5532:5432"]);
        // internal wiring is offset-blind: the API still reaches postgres
        // and the node at their in-network ports
        let env = api_env(&s);
        assert!(env.contains("PG_PORT=5432"));
        assert!(!env.contains("5532"), "offset leaked into internal wiring");

        // the default deployment keeps the historical naming and ports
        let s = deployment(TESTNET_FULL);
        assert_eq!(node_service(&s).container_name, "stacks-node");
        assert_eq!(postgres_service(&s).container_name, "stacks-postgres");
        assert_eq!(node_service(&s).ports[0], "20443:20443");
    }

    #[test]
    fn secret_bearing_rendered_files_are_owner_only() {
        use std::os::unix::fs::PermissionsExt;
        let dir = std::env::temp_dir().join(format!("stacksup-perm-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        render(&deployment(TESTNET_FULL), &dir).unwrap();
        for f in [
            "rendered/stacks-node/Config.toml",
            "rendered/stacks-signer/signer.toml",
            "rendered/stacks-api/.env",
            "rendered/stacks-mesh-api/.env",
            "rendered/secrets/pg_password",
        ] {
            let mode = std::fs::metadata(dir.join(f)).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o600, "{f} should be 0600");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn compose_file_embeds_project_name() {
        let dir = std::env::temp_dir().join(format!("stacksup-name-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let mut s = deployment(TESTNET_FULL);
        s.name = "testnet-b".into();
        render(&s, &dir).unwrap();
        let compose: serde_yaml::Value =
            serde_yaml::from_str(&std::fs::read_to_string(compose_file(&dir)).unwrap()).unwrap();
        assert_eq!(compose["name"].as_str(), Some("testnet-b"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    const SIDEKICK_FULL: &str = "network = \"testnet\"\n[stacks-node]\nmode = \"enabled\"\nrole = \"signer-host\"\n[stacks-signer]\nmode = \"enabled\"\n[stacks-api]\nmode = \"enabled\"\n[postgres]\nmode = \"enabled\"\n[signer-sidekick]\nmode = \"enabled\"\nmanager_principal = \"SP000000000000000000002Q6VF78.signer-manager\"";

    fn sidekick_deployment() -> Deployment {
        let mut d = deployment(SIDEKICK_FULL);
        d.signer_sidekick.auth_token = Some("test-sidekick-token".into());
        d
    }

    #[test]
    fn sidekick_env_wires_node_api_and_telemetry() {
        let d = sidekick_deployment();
        let env = sidekick_env(&d);
        // sidekick accepts the plain network name ("pox5-testnet" is only an alias upstream)
        assert!(env.contains("SIDEKICK_NETWORK=testnet"), "got: {env}");
        assert!(env.contains("STACKS_NODE_RPC_URL=http://stacks-node:20443"));
        // managed stacks-api is the indexed API by default
        assert!(env.contains("STACKS_API_URL=http://stacks-api:3999"));
        assert!(
            env.contains("SIDEKICK_MANAGER_PRINCIPAL=SP000000000000000000002Q6VF78.signer-manager")
        );
        assert!(env.contains("SIDEKICK_AUTH_TOKEN=test-sidekick-token"));
        assert!(env.contains("SIDEKICK_ENGINE_MODE=observe"));
        // managed node + signer -> direct telemetry endpoints
        assert!(env.contains("STACKS_NODE_METRICS_URL=http://stacks-node:9153/metrics"));
        assert!(env.contains("STACKS_SIGNER_MONITORING_URL=http://stacks-signer:30001"));

        // no managed API -> the network's Hiro API
        let mut d = deployment(
            "network = \"testnet\"\n[stacks-node]\nmode = \"enabled\"\nrole = \"signer-host\"\n[stacks-signer]\nmode = \"enabled\"\n[signer-sidekick]\nmode = \"enabled\"\nmanager_principal = \"SP000000000000000000002Q6VF78.signer-manager\"",
        );
        d.signer_sidekick.auth_token = Some("test-sidekick-token".into());
        assert!(
            sidekick_env(&d).contains("STACKS_API_URL=https://api.testnet.hiro.so"),
            "got: {}",
            sidekick_env(&d)
        );
    }

    #[test]
    fn sidekick_service_hardening_networks_and_ports() {
        let d = sidekick_deployment();
        let svc = sidekick_service(&d);
        // loopback dashboard on 3997 host-side; container keeps 3998
        assert_eq!(svc.ports, vec!["127.0.0.1:3997:3998"]);
        // core (node+signer) plus services (managed API is its indexed API)
        assert_eq!(svc.networks, vec!["core", "services"]);
        assert!(svc.read_only);
        assert_eq!(svc.cap_drop, vec!["ALL"]);
        assert!(svc.volumes.iter().any(|v| v == "sidekick-data:/data"));

        // explicit external API URL -> no services membership
        let mut d = sidekick_deployment();
        d.signer_sidekick.stacks_api_url = Some("https://api.example.com".into());
        assert_eq!(sidekick_service(&d).networks, vec!["core"]);
    }

    #[test]
    fn sidekick_enables_node_and_signer_telemetry_endpoints() {
        let with = sidekick_deployment();
        assert!(node_config_toml(&with).contains("prometheus_bind = \"0.0.0.0:9153\""));
        assert!(signer_config_toml(&with).contains("metrics_endpoint = \"0.0.0.0:30001\""));
        // ... and ONLY when sidekick is enabled
        let without = deployment(TESTNET_FULL);
        assert!(!node_config_toml(&without).contains("prometheus_bind"));
        assert!(!signer_config_toml(&without).contains("metrics_endpoint"));
    }

    #[test]
    fn render_with_user_provided_sidekick_profiles() {
        let dir =
            std::env::temp_dir().join(format!("stacksup-sidekick-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        // Pre-place the profile dirs: user-managed, so render must not fetch or overwrite.
        for sub in ["trusted-managers", "network-compatibility"] {
            std::fs::create_dir_all(dir.join("rendered/signer-sidekick").join(sub)).unwrap();
        }
        std::fs::write(
            dir.join("rendered/signer-sidekick/trusted-managers/mine.json"),
            "{}",
        )
        .unwrap();

        let d = sidekick_deployment();
        render(&d, &dir).unwrap();

        let compose_text = std::fs::read_to_string(compose_file(&dir)).unwrap();
        let compose: serde_yaml::Value = serde_yaml::from_str(&compose_text).unwrap();
        assert!(
            compose["services"]
                .as_mapping()
                .unwrap()
                .contains_key("signer-sidekick")
        );
        assert!(compose["volumes"].get("sidekick-data").is_some());
        // user-provided profiles untouched
        assert!(
            dir.join("rendered/signer-sidekick/trusted-managers/mine.json")
                .exists()
        );
        // env is owner-only (auth token inside)
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(dir.join("rendered/signer-sidekick/.env"))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn networks_isolate_signer_from_api_side() {
        // Full mainnet stack: three networks, least membership everywhere.
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"enabled\"\nrole = \"signer-host\"\n[stacks-signer]\nmode = \"enabled\"\n[stacks-api]\nmode = \"enabled\"\n[stacks-mesh-api]\nmode = \"enabled\"\n[postgres]\nmode = \"enabled\"",
        );
        assert_eq!(bitcoind_service(&s).networks, vec!["bitcoin"]);
        // the node bridges all three — everything talks to it
        assert_eq!(
            node_service(&s).networks,
            vec!["bitcoin", "core", "services"]
        );
        // the signer shares ONLY `core` with the node: unreachable from the
        // api/mesh/postgres side, and no direct line to bitcoind
        assert_eq!(signer_service(&s).networks, vec!["core"]);
        assert_eq!(api_service(&s).networks, vec!["services"]);
        assert_eq!(mesh_api_service(&s).networks, vec!["services"]);
        assert_eq!(postgres_service(&s).networks, vec!["services"]);

        // node alone: just `core`, no service networks dangling
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"external\"\nhost = \"h\"\n[stacks-node]\nmode = \"enabled\"",
        );
        assert_eq!(node_service(&s).networks, vec!["core"]);
    }

    #[test]
    fn apply_to_your_node_only_for_push_edges() {
        // external node + enabled api -> snippet with the api observer
        let s = deployment(
            "network = \"testnet\"\n[stacks-node]\nmode = \"external\"\nrpc_host = \"h\"\n[stacks-api]\nmode = \"enabled\"\n[postgres]\nmode = \"enabled\"",
        );
        let snippet = apply_to_your_node(&s).expect("push edge needs the snippet");
        assert!(snippet.contains("[[events_observer]]"));
        // external node with nothing to push to -> no snippet
        let s = deployment(
            "network = \"testnet\"\n[stacks-node]\nmode = \"external\"\nrpc_host = \"h\"",
        );
        assert!(apply_to_your_node(&s).is_none());
    }

    #[test]
    fn render_writes_expected_tree_and_valid_compose() {
        let dir = std::env::temp_dir().join(format!("stacksup-render-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let s = deployment(TESTNET_FULL);
        render(&s, &dir).unwrap();

        let compose_text = std::fs::read_to_string(compose_file(&dir)).unwrap();
        let compose: serde_yaml::Value = serde_yaml::from_str(&compose_text).unwrap();
        let services = compose["services"].as_mapping().unwrap();
        for name in [
            "stacks-node",
            "stacks-signer",
            "stacks-api",
            "stacks-mesh-api",
            "postgres",
        ] {
            assert!(services.contains_key(name), "compose missing {name}");
        }
        // testnet must NOT render a managed bitcoind
        assert!(!services.contains_key("bitcoind"));
        // ... so only the networks with members are declared
        let networks = compose["networks"].as_mapping().unwrap();
        assert!(networks.contains_key("core") && networks.contains_key("services"));
        assert!(!networks.contains_key("bitcoin"));
        assert!(dir.join("rendered/stacks-node/Config.toml").exists());
        assert!(dir.join("rendered/stacks-api/.env").exists());
        assert!(dir.join("chainstate/stacks-node").is_dir());

        let _ = std::fs::remove_dir_all(&dir);
    }
}
