//! Renders `stacks.toml` into everything the stack actually runs on, laid out under the
//! `--data-dir`:
//!
//!   <data-dir>/rendered/   compose file + per-service configs (regenerated)
//!   <data-dir>/chainstate/ service state: chainstate, Postgres, signer db
//!
//! Service state is bind-mounted from `chainstate/` (not named Docker volumes) so the entire stack
//! — configs and data — lives where the operator said.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::Result;
use serde::Serialize;

use crate::config::{Deployment, ServiceMode};
use crate::utils::secrets;
use crate::utils::services::*;

pub const COMPOSE_PROJECT: &str = "stacks";

/// Docker networks, split so a compromised API-side container cannot reach
/// the signer (or bitcoind) directly. Each service joins only the networks
/// it needs; the node bridges all three because everything talks to it.
const NET_BITCOIN: &str = "bitcoin"; // bitcoind + node
const NET_CORE: &str = "core"; // node + signer
const NET_SERVICES: &str = "services"; // api + mesh + postgres (+ node for RPC/events)

/// Path of the compose file within a data dir.
pub fn compose_file(data_dir: &Path) -> PathBuf {
    data_dir.join("rendered/docker-compose.yml")
}

const GENERATED_HEADER: &str = "# GENERATED by `stacksup config render` — edit stacks.toml instead; changes here will be overwritten.\n";

/// Events the stacks-api observer subscribes to (everywhere it is wired).
///
/// "*" delivers exactly /new_block (with all events unfiltered), /new_burn_block, /new_mempool_tx,
/// and /drop_mempool_tx — and does NOT include /stackerdb_chunks or /proposal_response (stacks-core
/// docs/event-dispatcher.md). Don't narrow it to ["stx", ...]: that filters /new_block's events to
/// STX-only, dropping the FT/NFT/contract events the API indexes. Invalid keys panic the node at
/// startup.
const API_EVENTS_KEYS: &str = r#"["*"]"#;

/// The Postgres database and schema the blockchain API owns. Fixed names: they only apply to the
/// managed Postgres (an external API brings its own database, and an external Postgres pairs with
/// an enabled API via these).
const API_PG_DATABASE: &str = "stacks_blockchain_api";
const API_PG_SCHEMA: &str = "stacks_blockchain_api";

#[derive(Serialize)]
struct ComposeFile {
    services: BTreeMap<String, ComposeService>,
    networks: BTreeMap<String, Option<()>>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    secrets: BTreeMap<String, ComposeSecret>,
}

#[derive(Serialize)]
struct ComposeSecret {
    file: String,
}

#[derive(Serialize, Default)]
struct ComposeService {
    image: String,
    container_name: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    entrypoint: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    command: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    ports: Vec<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    environment: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    env_file: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    volumes: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    depends_on: Vec<String>,
    restart: String,
    networks: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    secrets: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    extra_hosts: Vec<String>,
}

impl ComposeService {
    fn new(name: &str, image: &str) -> Self {
        // Namespace generic names (postgres, bitcoind) under the project
        // prefix; stacks-* names are already unambiguous.
        let container_name = if name.starts_with("stacks-") {
            name.to_string()
        } else {
            format!("{COMPOSE_PROJECT}-{name}")
        };
        ComposeService {
            image: image.into(),
            container_name,
            restart: "unless-stopped".into(),
            // Every builder sets its own network membership (least access).
            networks: Vec::new(),
            // Lets managed services reach "external" services running on the
            // operator's localhost — a common setup that trips people up.
            extra_hosts: vec!["host.docker.internal:host-gateway".into()],
            ..Default::default()
        }
    }
}

pub fn render(deployment: &Deployment, data_dir: &Path) -> Result<PathBuf> {
    let dir = data_dir.join("rendered");
    std::fs::create_dir_all(&dir)?;

    let mut compose = ComposeFile {
        services: BTreeMap::new(),
        networks: BTreeMap::new(),
        secrets: BTreeMap::new(),
    };

    // Pre-create bind-mount sources so docker doesn't create them root-owned.
    let chainstate_subdir = |name: &str| -> Result<()> {
        std::fs::create_dir_all(data_dir.join("chainstate").join(name))?;
        Ok(())
    };

    if deployment.bitcoind.mode == ServiceMode::Enabled {
        chainstate_subdir("bitcoind")?;
        compose
            .services
            .insert("bitcoind".into(), bitcoind_service(deployment));
    }

    if deployment.stacks_node.mode == ServiceMode::Enabled {
        chainstate_subdir("stacks-node")?;
        std::fs::create_dir_all(dir.join("stacks-node"))?;
        std::fs::write(
            dir.join("stacks-node/Config.toml"),
            format!("{GENERATED_HEADER}{}", node_config_toml(deployment)),
        )?;
        compose
            .services
            .insert("stacks-node".into(), node_service(deployment));
    }

    if deployment.stacks_signer.mode == ServiceMode::Enabled {
        chainstate_subdir("stacks-signer")?;
        std::fs::create_dir_all(dir.join("stacks-signer"))?;
        std::fs::write(
            dir.join("stacks-signer/signer.toml"),
            format!("{GENERATED_HEADER}{}", signer_config_toml(deployment)),
        )?;
        compose
            .services
            .insert("stacks-signer".into(), signer_service(deployment));
    }

    if deployment.stacks_api.mode == ServiceMode::Enabled {
        std::fs::create_dir_all(dir.join("stacks-api"))?;
        std::fs::write(
            dir.join("stacks-api/.env"),
            format!("{GENERATED_HEADER}{}", api_env(deployment)),
        )?;
        compose
            .services
            .insert("stacks-api".into(), api_service(deployment));
    }

    if deployment.stacks_mesh_api.mode == ServiceMode::Enabled {
        std::fs::create_dir_all(dir.join("stacks-mesh-api"))?;
        std::fs::write(
            dir.join("stacks-mesh-api/.env"),
            format!("{GENERATED_HEADER}{}", mesh_api_env(deployment)),
        )?;
        compose
            .services
            .insert("stacks-mesh-api".into(), mesh_api_service(deployment));
    }

    if deployment.postgres.mode == ServiceMode::Enabled {
        chainstate_subdir("postgres")?;
        std::fs::create_dir_all(data_dir.join("downloads"))?;
        std::fs::create_dir_all(dir.join("secrets"))?;
        secrets::write_0600(
            &dir.join("secrets/pg_password"),
            deployment.postgres.password.as_deref().unwrap_or_default(),
        )?;
        compose.secrets.insert(
            "pg_password".into(),
            ComposeSecret {
                file: "./secrets/pg_password".into(),
            },
        );
        compose
            .services
            .insert("postgres".into(), postgres_service(deployment));
    }

    // Declare exactly the networks the rendered services joined.
    for svc in compose.services.values() {
        for net in &svc.networks {
            compose.networks.entry(net.clone()).or_insert(None);
        }
    }

    let yaml = serde_yaml::to_string(&compose)?;
    std::fs::write(compose_file(data_dir), format!("{GENERATED_HEADER}{yaml}"))?;

    // Reversed (push) edges we can't wire ourselves: emit the node-side config.
    if deployment.stacks_node.mode == ServiceMode::External
        && let Some(snippet) = apply_to_your_node(deployment)
    {
        std::fs::write(dir.join("apply-to-your-node.toml"), snippet)?;
    }

    Ok(dir)
}

fn bitcoind_service(deployment: &Deployment) -> ComposeService {
    let rpc = bitcoind_rpc_port(deployment);
    let p2p = bitcoind_p2p_port(deployment);
    let mut svc = ComposeService::new("bitcoind", &bitcoind_image(deployment));
    svc.command = vec![
        "-server=1".into(),
        "-txindex=0".into(),
        format!("-chain={}", deployment.net.bitcoind.chain),
        "-rpcbind=0.0.0.0".into(),
        "-rpcallowip=0.0.0.0/0".into(),
        // A salted hash — unlike -rpcpassword, safe to expose via docker
        // inspect. The plaintext lives in secrets.toml and the node's
        // mounted Config.toml only. The `$` separating salt from digest must
        // be `$$` in the compose file or interpolation swallows the digest.
        format!(
            "-rpcauth={}",
            secrets::bitcoind_rpcauth(
                deployment.bitcoind.rpc_user.as_deref().unwrap_or_default(),
                deployment
                    .bitcoind
                    .rpc_password
                    .as_deref()
                    .unwrap_or_default(),
            )
            .replace('$', "$$")
        ),
    ];
    // Loopback-bind the RPC port: every container carries a
    // host.docker.internal alias, so a 0.0.0.0 publish would let API-side
    // containers reach bitcoind through the host, bypassing the network
    // split. Operators still get bitcoin-cli on localhost. Only an external
    // node (running off-host) needs the wide binding. P2P stays open — it
    // exists to accept peers.
    let rpc_publish = if deployment.stacks_node.mode == ServiceMode::External {
        format!("{rpc}:{rpc}")
    } else {
        format!("127.0.0.1:{rpc}:{rpc}")
    };
    svc.ports = vec![rpc_publish, format!("{p2p}:{p2p}")];
    svc.volumes = vec!["../chainstate/bitcoind:/home/bitcoin/.bitcoin".into()];
    svc.networks = vec![NET_BITCOIN.into()];
    svc
}

fn node_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new("stacks-node", &stacks_node_image(deployment));
    svc.command = vec![
        "stacks-node".into(),
        "start".into(),
        "--config".into(),
        "/etc/stacks/Config.toml".into(),
    ];
    svc.ports = vec![
        format!("{NODE_RPC_PORT}:{NODE_RPC_PORT}"),
        format!("{NODE_P2P_PORT}:{NODE_P2P_PORT}"),
    ];
    svc.volumes = vec![
        "./stacks-node/Config.toml:/etc/stacks/Config.toml:ro".into(),
        "../chainstate/stacks-node:/stacks-blockchain".into(),
    ];
    if deployment.bitcoind.mode == ServiceMode::Enabled {
        svc.depends_on.push("bitcoind".into());
    }
    // The node pushes events to the API; if the API is down at boot the node
    // retries, but starting after the API avoids stalling block processing.
    if deployment.stacks_api.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-api".into());
    }
    // Always on `core` (its home even with no signer); `bitcoin` only with a
    // managed bitcoind; `services` only when an API-side consumer needs its
    // RPC or receives its event pushes.
    svc.networks = vec![NET_CORE.into()];
    if deployment.bitcoind.mode == ServiceMode::Enabled {
        svc.networks.insert(0, NET_BITCOIN.into());
    }
    if deployment.stacks_api.mode == ServiceMode::Enabled
        || deployment.stacks_mesh_api.mode == ServiceMode::Enabled
    {
        svc.networks.push(NET_SERVICES.into());
    }
    svc
}

fn signer_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new("stacks-signer", &stacks_signer_image(deployment));
    svc.command = vec![
        "stacks-signer".into(),
        "run".into(),
        "-c".into(),
        "/etc/stacks/signer.toml".into(),
    ];
    svc.volumes = vec![
        "./stacks-signer/signer.toml:/etc/stacks/signer.toml:ro".into(),
        "../chainstate/stacks-signer:/var/lib/stacks-signer".into(),
    ];
    if deployment.stacks_node.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-node".into());
    }
    svc.networks = vec![NET_CORE.into()];
    svc
}

fn api_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new("stacks-api", &stacks_api_image(deployment));
    svc.ports = vec![format!("{API_PORT}:{API_PORT}")];
    svc.env_file = vec!["./stacks-api/.env".into()];
    if deployment.postgres.mode == ServiceMode::Enabled {
        svc.depends_on.push("postgres".into());
    }
    svc.networks = vec![NET_SERVICES.into()];
    svc
}

fn mesh_api_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new("stacks-mesh-api", &stacks_mesh_api_image(deployment));
    svc.ports = vec![format!("{MESH_API_PORT}:{MESH_API_PORT}")];
    svc.env_file = vec!["./stacks-mesh-api/.env".into()];
    if deployment.stacks_node.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-node".into());
    }
    svc.networks = vec![NET_SERVICES.into()];
    svc
}

/// Postgres major from the configured version tag: "17" -> 17,
/// "17.5-alpine" -> 17, "latest"/absent -> None.
fn postgres_major(deployment: &Deployment) -> Option<u32> {
    deployment
        .postgres
        .version
        .as_deref()?
        .split(['.', '-'])
        .next()?
        .parse()
        .ok()
}

fn postgres_service(deployment: &Deployment) -> ComposeService {
    let mut svc = ComposeService::new("postgres", &postgres_image(deployment));
    svc.ports = vec![format!("{POSTGRES_PORT}:{POSTGRES_PORT}")];
    svc.networks = vec![NET_SERVICES.into()];
    svc.environment.insert(
        "POSTGRES_USER".into(),
        deployment
            .postgres
            .user
            .clone()
            .unwrap_or_else(|| "postgres".into()),
    );
    // Password arrives via a compose secret file, not container env —
    // `docker inspect` shows only the path.
    svc.environment.insert(
        "POSTGRES_PASSWORD_FILE".into(),
        "/run/secrets/pg_password".into(),
    );
    svc.secrets = vec!["pg_password".into()];
    svc.environment
        .insert("POSTGRES_DB".into(), API_PG_DATABASE.into());
    // Postgres 18+ images keep data in a version-specific subdirectory and
    // require the mount at /var/lib/postgresql (enabling pg_upgrade across
    // majors); images <= 17 use PGDATA=/var/lib/postgresql/data and need the
    // mount there. Unknown majors (e.g. `latest`) get the 18+ convention.
    let data_target = match postgres_major(deployment) {
        Some(major) if major <= 17 => "/var/lib/postgresql/data",
        _ => "/var/lib/postgresql",
    };
    svc.volumes = vec![
        format!("../chainstate/postgres:{data_target}"),
        // Read-only view of downloaded archives so pg_restore (which needs a
        // seekable file, not stdin) can restore dumps fetched by
        // `stacksup chainstate download`.
        "../downloads:/downloads:ro".into(),
    ];

    // Ensure the API's schema exists on EVERY boot, not just first init —
    // /docker-entrypoint-initdb.d only runs on an empty data directory.
    // The schema creator runs as a background job while postgres is exec'd
    // as PID 1, so SIGTERM from `stacksup stop` reaches postgres directly and
    // shutdown is clean (a backgrounded postgres under bash would be
    // SIGKILLed after the grace period instead).
    let user = deployment
        .postgres
        .user
        .clone()
        .unwrap_or_else(|| "postgres".into());
    let db = API_PG_DATABASE;
    svc.entrypoint = vec![
        "/bin/bash".into(),
        "-c".into(),
        format!(
            "(until pg_isready -U {user} -d {db}; do sleep 3; done && \
             psql -U {user} -d {db} -c 'CREATE SCHEMA IF NOT EXISTS {API_PG_SCHEMA};' || true) & \
             exec docker-entrypoint.sh postgres"
        ),
    ];
    svc
}

/// The stacks-node Config.toml. Cross-service values (bitcoind endpoint, event
/// observers, signer auth) are derived from the same `Deployment` the other configs
/// come from — matched by construction. The testnet shape mirrors
/// stacks-core's sample/conf/testnet-follower-conf.toml.
fn node_config_toml(deployment: &Deployment) -> String {
    let net = &deployment.net;
    let mut out = String::new();

    out.push_str("[node]\n");
    out.push_str("working_dir = \"/stacks-blockchain\"\n");
    out.push_str(&format!("rpc_bind = \"0.0.0.0:{NODE_RPC_PORT}\"\n"));
    out.push_str(&format!("p2p_bind = \"0.0.0.0:{NODE_P2P_PORT}\"\n"));
    if let Some(bootstrap) = &net.node.bootstrap_node {
        out.push_str(&format!("bootstrap_node = \"{bootstrap}\"\n"));
    }
    if deployment.stacks_signer.mode != ServiceMode::Disabled {
        out.push_str("stacker = true\n");
    } else {
        out.push_str("miner = false\nstacker = false\n");
    }
    if let Some(extra) = &net.node.node_extra {
        out.push_str(extra.trim());
        out.push('\n');
    }
    out.push('\n');

    out.push_str("[connection_options]\n");
    out.push_str(&format!(
        "auth_token = \"{}\"\n",
        node_auth_token(deployment)
    ));
    out.push_str("private_neighbors = false\n\n");

    out.push_str("[burnchain]\n");
    out.push_str(&format!(
        "mode = \"{}\"\nchain = \"bitcoin\"\n",
        net.node.burnchain_mode
    ));
    // Burnchain endpoint: managed/external bitcoind, else the network's
    // hosted default (validation guarantees one of these exists for a node).
    if let Some(host) = bitcoind_host(deployment).or_else(|| net.bitcoind.default_host.clone()) {
        out.push_str(&format!("peer_host = \"{host}\"\n"));
        out.push_str(&format!(
            "rpc_port = {}\npeer_port = {}\n",
            bitcoind_rpc_port(deployment),
            bitcoind_p2p_port(deployment)
        ));
        // Credentials: our managed bitcoind always has them (tool defaults);
        // an external one only when both are explicitly configured —
        // validation rejects partial credentials, so no silent fallbacks.
        if deployment.bitcoind.mode == ServiceMode::Enabled {
            out.push_str(&format!(
                "username = \"{}\"\npassword = \"{}\"\n",
                deployment.bitcoind.rpc_user.as_deref().unwrap_or_default(),
                deployment
                    .bitcoind
                    .rpc_password
                    .as_deref()
                    .unwrap_or_default(),
            ));
        } else if let (Some(user), Some(password)) = (
            &deployment.bitcoind.rpc_user,
            &deployment.bitcoind.rpc_password,
        ) {
            out.push_str(&format!(
                "username = \"{user}\"\npassword = \"{password}\"\n"
            ));
        }
    }
    if let (Some(prepare), Some(reward)) = (net.node.pox_prepare_length, net.node.pox_reward_length)
    {
        out.push_str(&format!(
            "pox_prepare_length = {prepare}\npox_reward_length = {reward}\n"
        ));
    }
    out.push('\n');

    if deployment.stacks_api.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[[events_observer]]\nendpoint = \"stacks-api:{API_EVENT_PORT}\"\nevents_keys = {API_EVENTS_KEYS}\ntimeout_ms = 300_000\n\n"
        ));
    } else if deployment.stacks_api.mode == ServiceMode::External
        && let (Some(host), Some(port)) = (
            &deployment.stacks_api.event_host,
            deployment.stacks_api.event_port,
        )
    {
        out.push_str(&format!(
                "[[events_observer]]\nendpoint = \"{host}:{port}\"\nevents_keys = {API_EVENTS_KEYS}\ntimeout_ms = 300_000\n\n"
            ));
    }

    if deployment.stacks_signer.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[[events_observer]]\nendpoint = \"stacks-signer:{SIGNER_ENDPOINT_PORT}\"\nevents_keys = [\"stackerdb\", \"block_proposal\", \"burn_blocks\"]\n\n"
        ));
    }

    for balance in &net.ustx_balances {
        out.push_str(&format!(
            "[[ustx_balance]]\naddress = \"{}\"\namount = {}\n\n",
            balance.address, balance.amount
        ));
    }
    for epoch in &net.epochs {
        out.push_str(&format!(
            "[[burnchain.epochs]]\nepoch_name = \"{}\"\nstart_height = {}\n\n",
            epoch.epoch_name, epoch.start_height
        ));
    }

    out
}

fn signer_config_toml(deployment: &Deployment) -> String {
    let node_host = node_rpc_host(deployment).unwrap_or_default();
    format!(
        r#"node_host = "{node_host}:{rpc_port}"
endpoint = "0.0.0.0:{endpoint_port}"
auth_password = "{auth}"
network = "{network}"
db_path = "/var/lib/stacks-signer/signerdb.sqlite"
# TODO(hackathon): source the signing key from a secrets file, never this rendered config
stacks_private_key = "REPLACE_ME"
"#,
        rpc_port = node_rpc_port(deployment),
        endpoint_port = SIGNER_ENDPOINT_PORT,
        auth = node_auth_token(deployment),
        network = deployment.network,
    )
}

/// The node's `connection_options.auth_token`, which the signer's
/// `auth_password` must match. External nodes bring their own token
/// (`[stacks-node] auth_token`); managed nodes use a tool-managed one.
/// The auth token shared by node config, signer, and mesh env — a single
/// deployment field, populated from secrets.toml (required by validation
/// whenever something consumes it).
fn node_auth_token(deployment: &Deployment) -> String {
    deployment
        .stacks_node
        .auth_token
        .clone()
        .unwrap_or_default()
}

fn api_env(deployment: &Deployment) -> String {
    let chain_id = format!("0x{:08x}", deployment.net.chain_id);
    let node_host = node_rpc_host(deployment).unwrap_or_default();
    let pg_host = postgres_host(deployment).unwrap_or_default();
    format!(
        r#"NODE_ENV=production
STACKS_CHAIN_ID={chain_id}
STACKS_BLOCKCHAIN_API_HOST=0.0.0.0
STACKS_BLOCKCHAIN_API_PORT={api_port}
STACKS_CORE_EVENT_HOST=0.0.0.0
STACKS_CORE_EVENT_PORT={event_port}
STACKS_CORE_RPC_HOST={node_host}
STACKS_CORE_RPC_PORT={node_rpc}
PG_HOST={pg_host}
PG_PORT={pg_port}
PG_USER={pg_user}
PG_PASSWORD={pg_password}
PG_DATABASE={pg_db}
PG_SCHEMA={pg_schema}
STACKS_API_STORE_RAW_EVENTS=false
TESTNET_BTC_FAUCET_ENABLED=false
TESTNET_STX_FAUCET_ENABLED=false
TESTNET_SBTC_FAUCET_ENABLED=false
"#,
        api_port = API_PORT,
        event_port = API_EVENT_PORT,
        node_rpc = node_rpc_port(deployment),
        pg_port = postgres_port(deployment),
        pg_schema = API_PG_SCHEMA,
        pg_user = deployment.postgres.user.as_deref().unwrap_or("postgres"),
        pg_password = deployment.postgres.password.as_deref().unwrap_or_default(),
        pg_db = API_PG_DATABASE,
    )
}

/// Env for the Stacks Mesh API (packages/api/src/env.ts is the schema of
/// record). Online mode needs the node's RPC endpoint and — critically — the
/// node's `connection_options.auth_token`, which this render guarantees
/// matches by deriving both from the same source. Cache sizes/TTLs and
/// BLOCK_HASH_MODE are left to the service's own defaults.
fn mesh_api_env(deployment: &Deployment) -> String {
    let node_host = node_rpc_host(deployment).unwrap_or_default();
    format!(
        r#"API_HOST=0.0.0.0
API_PORT={api_port}
MODE=online
STACKS_CORE_RPC_SCHEME=http
STACKS_CORE_RPC_HOST={node_host}
STACKS_CORE_RPC_PORT={node_rpc}
STACKS_CORE_RPC_AUTH_TOKEN={auth_token}
"#,
        api_port = MESH_API_PORT,
        node_rpc = node_rpc_port(deployment),
        auth_token = node_auth_token(deployment),
    )
}

/// Config the user must apply to their *external* node so push edges
/// (events to the API, signer wiring) actually close.
fn apply_to_your_node(deployment: &Deployment) -> Option<String> {
    let mut out = String::from(
        "# Add these blocks to your stacks-node config, then restart it.\n\
         # Verify events are flowing afterwards with `stacksup config check`.\n\n",
    );
    let mut needed = false;

    if deployment.stacks_api.mode == ServiceMode::Enabled {
        // TODO(hackathon): make the advertised host configurable; the external
        // node must be able to reach the machine running this stack.
        out.push_str(&format!(
            "[[events_observer]]\nendpoint = \"<this-machine>:{API_EVENT_PORT}\"\nevents_keys = {API_EVENTS_KEYS}\n\n"
        ));
        needed = true;
    }
    if deployment.stacks_signer.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[node]\nstacker = true\n\n\
             [connection_options]\nauth_token = \"{}\"\n\n\
             [[events_observer]]\nendpoint = \"<this-machine>:{SIGNER_ENDPOINT_PORT}\"\nevents_keys = [\"stackerdb\", \"block_proposal\", \"burn_blocks\"]\n\n",
            node_auth_token(deployment)
        ));
        needed = true;
    }

    needed.then_some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Parse and merge the same test secrets `load()` would pull from a
    /// secrets.toml, so generators see a post-merge deployment. Managed
    /// bitcoind gets credentials; external keeps whatever the toml set.
    fn deployment(toml_str: &str) -> Deployment {
        let mut d = crate::config::test_deployment(toml_str);
        d.postgres
            .password
            .get_or_insert_with(|| "test-pg-password".into());
        d.stacks_node
            .auth_token
            .get_or_insert_with(|| "test-node-token".into());
        if d.bitcoind.mode == ServiceMode::Enabled {
            d.bitcoind.rpc_user.get_or_insert_with(|| "stacksup".into());
            d.bitcoind
                .rpc_password
                .get_or_insert_with(|| "test-btc-password".into());
        }
        d
    }

    const TESTNET_FULL: &str = "network = \"testnet\"\n[stacks-node]\nmode = \"enabled\"\nrole = \"signer-host\"\n[stacks-signer]\nmode = \"enabled\"\n[stacks-api]\nmode = \"enabled\"\n[stacks-mesh-api]\nmode = \"enabled\"\n[postgres]\nmode = \"enabled\"";

    #[test]
    fn testnet_node_config_matches_reference_shape() {
        let s = deployment("network = \"testnet\"\n[stacks-node]\nmode = \"enabled\"");
        let toml_text = node_config_toml(&s);
        let parsed: toml::Value =
            toml::from_str(&toml_text).expect("rendered node config is valid TOML");
        assert_eq!(parsed["burnchain"]["mode"].as_str(), Some("krypton"));
        assert_eq!(
            parsed["burnchain"]["peer_host"].as_str(),
            Some("bitcoin.regtest.hiro.so")
        );
        assert_eq!(parsed["burnchain"]["rpc_port"].as_integer(), Some(18443));
        assert!(
            parsed["node"]["bootstrap_node"]
                .as_str()
                .unwrap()
                .contains("seed.testnet.hiro.so")
        );
        // follower: explicitly not mining or stacking
        assert_eq!(parsed["node"]["miner"].as_bool(), Some(false));
        assert_eq!(parsed["node"]["stacker"].as_bool(), Some(false));
        assert_eq!(parsed["ustx_balance"].as_array().unwrap().len(), 12);
        assert_eq!(parsed["burnchain"]["epochs"].as_array().unwrap().len(), 14);
    }

    #[test]
    fn signer_flips_stacker_and_shares_auth_token() {
        let s = deployment(TESTNET_FULL);
        let node: toml::Value = toml::from_str(&node_config_toml(&s)).unwrap();
        assert_eq!(node["node"]["stacker"].as_bool(), Some(true));
        let token = node["connection_options"]["auth_token"]
            .as_str()
            .unwrap()
            .to_string();
        // signer auth_password and mesh env token must match the node's token
        assert!(signer_config_toml(&s).contains(&format!("auth_password = \"{token}\"")));
        assert!(mesh_api_env(&s).contains(&format!("STACKS_CORE_RPC_AUTH_TOKEN={token}")));
    }

    #[test]
    fn api_env_wires_postgres_and_schema() {
        let s = deployment(TESTNET_FULL);
        let env = api_env(&s);
        assert!(env.contains("PG_HOST=postgres"));
        assert!(env.contains(&format!("PG_DATABASE={API_PG_DATABASE}")));
        assert!(env.contains(&format!("PG_SCHEMA={API_PG_SCHEMA}")));
        assert!(env.contains("STACKS_CHAIN_ID=0x80000000"));
    }

    #[test]
    fn postgres_mount_depends_on_major() {
        let pg17 =
            deployment("network = \"testnet\"\n[postgres]\nmode = \"enabled\"\nversion = \"17\"");
        assert_eq!(postgres_major(&pg17), Some(17));
        assert!(postgres_service(&pg17).volumes[0].ends_with(":/var/lib/postgresql/data"));
        let latest = deployment("network = \"testnet\"\n[postgres]\nmode = \"enabled\"");
        assert_eq!(postgres_major(&latest), None);
        assert!(postgres_service(&latest).volumes[0].ends_with(":/var/lib/postgresql"));
        assert_eq!(
            postgres_major(&deployment(
                "network = \"testnet\"\n[postgres]\nversion = \"17.5-alpine\""
            )),
            Some(17)
        );
    }

    #[test]
    fn external_bitcoind_credentials_all_or_nothing() {
        // both set -> rendered verbatim
        let d = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"external\"\nhost = \"h\"\nrpc_user = \"u\"\nrpc_password = \"p\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let cfg = node_config_toml(&d);
        assert!(cfg.contains("username = \"u\"") && cfg.contains("password = \"p\""));
        // none set -> no credential lines, no silent defaults
        let d = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"external\"\nhost = \"h\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let cfg = node_config_toml(&d);
        assert!(!cfg.contains("username"));
        // managed -> generated secrets, never hardcoded defaults
        let d = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let cfg = node_config_toml(&d);
        assert!(cfg.contains("username = \"stacksup\""));
        assert!(cfg.contains("password = \"test-btc-password\""));
    }

    #[test]
    fn bitcoind_rpc_port_is_loopback_unless_node_is_external() {
        // managed node talks over the docker network; the host publish is
        // diagnostic only -> loopback (blocks the host.docker.internal bypass)
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let ports = bitcoind_service(&s).ports;
        assert!(ports[0].starts_with("127.0.0.1:"), "got: {ports:?}");
        assert!(!ports[1].starts_with("127.0.0.1:"), "p2p must accept peers");

        // an off-host node needs the wide binding
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"external\"\nrpc_host = \"h\"",
        );
        assert!(!bitcoind_service(&s).ports[0].starts_with("127.0.0.1:"));
    }

    #[test]
    fn bitcoind_rpcauth_dollar_is_escaped_for_compose() {
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"enabled\"",
        );
        let rpcauth = bitcoind_service(&s)
            .command
            .iter()
            .find(|a| a.starts_with("-rpcauth="))
            .unwrap()
            .clone();
        // `$$` survives compose interpolation as a literal `$`; a bare `$`
        // would swallow the digest ("variable is not set" -> blank).
        assert!(rpcauth.contains("$$"), "got: {rpcauth}");
        assert!(!rpcauth.replace("$$", "").contains('$'));
    }

    #[test]
    fn networks_isolate_signer_from_api_side() {
        // Full mainnet stack: three networks, least membership everywhere.
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"enabled\"\n[stacks-node]\nmode = \"enabled\"\nrole = \"signer-host\"\n[stacks-signer]\nmode = \"enabled\"\n[stacks-api]\nmode = \"enabled\"\n[stacks-mesh-api]\nmode = \"enabled\"\n[postgres]\nmode = \"enabled\"",
        );
        assert_eq!(bitcoind_service(&s).networks, vec!["bitcoin"]);
        // the node bridges all three — everything talks to it
        assert_eq!(
            node_service(&s).networks,
            vec!["bitcoin", "core", "services"]
        );
        // the signer shares ONLY `core` with the node: unreachable from the
        // api/mesh/postgres side, and no direct line to bitcoind
        assert_eq!(signer_service(&s).networks, vec!["core"]);
        assert_eq!(api_service(&s).networks, vec!["services"]);
        assert_eq!(mesh_api_service(&s).networks, vec!["services"]);
        assert_eq!(postgres_service(&s).networks, vec!["services"]);

        // node alone: just `core`, no service networks dangling
        let s = deployment(
            "network = \"mainnet\"\n[bitcoind]\nmode = \"external\"\nhost = \"h\"\n[stacks-node]\nmode = \"enabled\"",
        );
        assert_eq!(node_service(&s).networks, vec!["core"]);
    }

    #[test]
    fn apply_to_your_node_only_for_push_edges() {
        // external node + enabled api -> snippet with the api observer
        let s = deployment(
            "network = \"testnet\"\n[stacks-node]\nmode = \"external\"\nrpc_host = \"h\"\n[stacks-api]\nmode = \"enabled\"\n[postgres]\nmode = \"enabled\"",
        );
        let snippet = apply_to_your_node(&s).expect("push edge needs the snippet");
        assert!(snippet.contains("[[events_observer]]"));
        // external node with nothing to push to -> no snippet
        let s = deployment(
            "network = \"testnet\"\n[stacks-node]\nmode = \"external\"\nrpc_host = \"h\"",
        );
        assert!(apply_to_your_node(&s).is_none());
    }

    #[test]
    fn render_writes_expected_tree_and_valid_compose() {
        let dir = std::env::temp_dir().join(format!("stacksup-render-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let s = deployment(TESTNET_FULL);
        render(&s, &dir).unwrap();

        let compose_text = std::fs::read_to_string(compose_file(&dir)).unwrap();
        let compose: serde_yaml::Value = serde_yaml::from_str(&compose_text).unwrap();
        let services = compose["services"].as_mapping().unwrap();
        for name in [
            "stacks-node",
            "stacks-signer",
            "stacks-api",
            "stacks-mesh-api",
            "postgres",
        ] {
            assert!(services.contains_key(name), "compose missing {name}");
        }
        // testnet must NOT render a managed bitcoind
        assert!(!services.contains_key("bitcoind"));
        // ... so only the networks with members are declared
        let networks = compose["networks"].as_mapping().unwrap();
        assert!(networks.contains_key("core") && networks.contains_key("services"));
        assert!(!networks.contains_key("bitcoin"));
        assert!(dir.join("rendered/stacks-node/Config.toml").exists());
        assert!(dir.join("rendered/stacks-api/.env").exists());
        assert!(dir.join("chainstate/stacks-node").is_dir());

        let _ = std::fs::remove_dir_all(&dir);
    }
}
