//! Renders `stacks.toml` into everything the stack actually runs on, laid out
//! under the `--data-dir`:
//!
//!   <data-dir>/rendered/   compose file + per-service configs (regenerated)
//!   <data-dir>/chainstate/ service state: chainstate, Postgres, signer db
//!
//! Service state is bind-mounted from `chainstate/` (not named Docker volumes) so
//! the entire stack — configs and data — lives where the operator said.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::Result;
use serde::Serialize;

use crate::config::{Network, ServiceMode, Stack};
use crate::services::*;

pub const COMPOSE_PROJECT: &str = "stacks";

/// The docker network every service in the stack joins.
const COMPOSE_NETWORK: &str = "stacks";

/// Path of the compose file within a data dir.
pub fn compose_file(data_dir: &Path) -> PathBuf {
    data_dir.join("rendered/docker-compose.yml")
}

const GENERATED_HEADER: &str =
    "# GENERATED by `stacks config render` — edit stacks.toml instead; changes here will be overwritten.\n";

/// Events the stacks-api observer subscribes to (everywhere it is wired).
///
/// "*" delivers exactly /new_block (with all events unfiltered), /new_burn_block,
/// /new_mempool_tx, and /drop_mempool_tx — and does NOT include /stackerdb_chunks
/// or /proposal_response (stacks-core docs/event-dispatcher.md). Don't narrow it
/// to ["stx", ...]: that filters /new_block's events to STX-only, dropping the
/// FT/NFT/contract events the API indexes. Invalid keys panic the node at startup.
const API_EVENTS_KEYS: &str = r#"["*"]"#;

/// The Postgres database and schema the blockchain API owns. Fixed names:
/// they only apply to the managed Postgres (an external API brings its own
/// database, and an external Postgres pairs with an enabled API via these).
const API_PG_DATABASE: &str = "stacks_blockchain_api";
const API_PG_SCHEMA: &str = "stacks_blockchain_api";

#[derive(Serialize)]
struct ComposeFile {
    services: BTreeMap<String, ComposeService>,
    networks: BTreeMap<String, Option<()>>,
}

#[derive(Serialize, Default)]
struct ComposeService {
    image: String,
    container_name: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    entrypoint: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    command: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    ports: Vec<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    environment: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    env_file: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    volumes: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    depends_on: Vec<String>,
    restart: String,
    networks: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    extra_hosts: Vec<String>,
}

impl ComposeService {
    fn new(name: &str, image: &str) -> Self {
        // Namespace generic names (postgres, bitcoind) under the project
        // prefix; stacks-* names are already unambiguous.
        let container_name = if name.starts_with("stacks-") {
            name.to_string()
        } else {
            format!("{COMPOSE_PROJECT}-{name}")
        };
        ComposeService {
            image: image.into(),
            container_name,
            restart: "unless-stopped".into(),
            networks: vec![COMPOSE_NETWORK.into()],
            // Lets managed services reach "external" services running on the
            // operator's localhost — a common setup that trips people up.
            extra_hosts: vec!["host.docker.internal:host-gateway".into()],
            ..Default::default()
        }
    }
}

pub fn render(stack: &Stack, data_dir: &Path) -> Result<PathBuf> {
    let dir = data_dir.join("rendered");
    std::fs::create_dir_all(&dir)?;

    let mut compose = ComposeFile {
        services: BTreeMap::new(),
        networks: BTreeMap::from([(COMPOSE_NETWORK.to_string(), None)]),
    };

    // Pre-create bind-mount sources so docker doesn't create them root-owned.
    let chainstate_subdir = |name: &str| -> Result<()> {
        std::fs::create_dir_all(data_dir.join("chainstate").join(name))?;
        Ok(())
    };

    if stack.bitcoind.mode == ServiceMode::Enabled {
        chainstate_subdir("bitcoind")?;
        compose.services.insert("bitcoind".into(), bitcoind_service(stack));
    }

    if stack.stacks_node.mode == ServiceMode::Enabled {
        chainstate_subdir("stacks-node")?;
        std::fs::create_dir_all(dir.join("stacks-node"))?;
        std::fs::write(
            dir.join("stacks-node/Config.toml"),
            format!("{GENERATED_HEADER}{}", node_config_toml(stack)),
        )?;
        compose.services.insert("stacks-node".into(), node_service(stack));
    }

    if stack.stacks_signer.mode == ServiceMode::Enabled {
        chainstate_subdir("stacks-signer")?;
        std::fs::create_dir_all(dir.join("stacks-signer"))?;
        std::fs::write(
            dir.join("stacks-signer/signer.toml"),
            format!("{GENERATED_HEADER}{}", signer_config_toml(stack)),
        )?;
        compose.services.insert("stacks-signer".into(), signer_service(stack));
    }

    if stack.stacks_api.mode == ServiceMode::Enabled {
        std::fs::create_dir_all(dir.join("stacks-api"))?;
        std::fs::write(
            dir.join("stacks-api/.env"),
            format!("{GENERATED_HEADER}{}", api_env(stack)),
        )?;
        compose.services.insert("stacks-api".into(), api_service(stack));
    }

    if stack.stacks_mesh_api.mode == ServiceMode::Enabled {
        compose.services.insert("stacks-mesh-api".into(), mesh_api_service(stack));
    }

    if stack.postgres.mode == ServiceMode::Enabled {
        chainstate_subdir("postgres")?;
        compose.services.insert("postgres".into(), postgres_service(stack));
    }

    let yaml = serde_yaml::to_string(&compose)?;
    std::fs::write(compose_file(data_dir), format!("{GENERATED_HEADER}{yaml}"))?;

    // Reversed (push) edges we can't wire ourselves: emit the node-side config.
    if stack.stacks_node.mode == ServiceMode::External {
        if let Some(snippet) = apply_to_your_node(stack) {
            std::fs::write(dir.join("apply-to-your-node.toml"), snippet)?;
        }
    }

    Ok(dir)
}

fn bitcoind_service(stack: &Stack) -> ComposeService {
    let rpc = bitcoind_rpc_port(stack.network);
    let p2p = bitcoind_p2p_port(stack.network);
    let mut svc = ComposeService::new("bitcoind", &bitcoind_image(stack));
    svc.command = vec![
        "-server=1".into(),
        "-txindex=0".into(),
        format!("-chain={}", if stack.network == Network::Mainnet { "main" } else { "test" }),
        "-rpcbind=0.0.0.0".into(),
        "-rpcallowip=0.0.0.0/0".into(),
        // TODO(hackathon): generate rpcauth instead of user/pass defaults
        "-rpcuser=stacks".into(),
        "-rpcpassword=stacks".into(),
    ];
    svc.ports = vec![format!("{rpc}:{rpc}"), format!("{p2p}:{p2p}")];
    svc.volumes = vec!["../chainstate/bitcoind:/home/bitcoin/.bitcoin".into()];
    svc
}

fn node_service(stack: &Stack) -> ComposeService {
    let mut svc = ComposeService::new("stacks-node", &stacks_node_image(stack));
    svc.command = vec!["stacks-node".into(), "start".into(), "--config".into(), "/etc/stacks/Config.toml".into()];
    svc.ports = vec![
        format!("{NODE_RPC_PORT}:{NODE_RPC_PORT}"),
        format!("{NODE_P2P_PORT}:{NODE_P2P_PORT}"),
    ];
    svc.volumes = vec![
        "./stacks-node/Config.toml:/etc/stacks/Config.toml:ro".into(),
        "../chainstate/stacks-node:/stacks-blockchain".into(),
    ];
    if stack.bitcoind.mode == ServiceMode::Enabled {
        svc.depends_on.push("bitcoind".into());
    }
    // The node pushes events to the API; if the API is down at boot the node
    // retries, but starting after the API avoids stalling block processing.
    if stack.stacks_api.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-api".into());
    }
    svc
}

fn signer_service(stack: &Stack) -> ComposeService {
    let mut svc = ComposeService::new("stacks-signer", &stacks_signer_image(stack));
    svc.command = vec!["stacks-signer".into(), "run".into(), "-c".into(), "/etc/stacks/signer.toml".into()];
    svc.volumes = vec![
        "./stacks-signer/signer.toml:/etc/stacks/signer.toml:ro".into(),
        "../chainstate/stacks-signer:/var/lib/stacks-signer".into(),
    ];
    if stack.stacks_node.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-node".into());
    }
    svc
}

fn api_service(stack: &Stack) -> ComposeService {
    let mut svc = ComposeService::new("stacks-api", &stacks_api_image(stack));
    svc.ports = vec![format!("{API_PORT}:{API_PORT}")];
    svc.env_file = vec!["./stacks-api/.env".into()];
    if stack.postgres.mode == ServiceMode::Enabled {
        svc.depends_on.push("postgres".into());
    }
    svc
}

fn mesh_api_service(stack: &Stack) -> ComposeService {
    // TODO(hackathon): confirm the mesh API's real config surface (env var
    // names, whether it also consumes node events).
    let mut svc = ComposeService::new("stacks-mesh-api", &stacks_mesh_api_image(stack));
    svc.ports = vec![format!("{MESH_API_PORT}:{MESH_API_PORT}")];
    let node_host = node_rpc_host(stack).unwrap_or_default();
    svc.environment.insert("STACKS_NODE_RPC_URL".into(), format!("http://{node_host}:{}", node_rpc_port(stack)));
    if stack.stacks_node.mode == ServiceMode::Enabled {
        svc.depends_on.push("stacks-node".into());
    }
    svc
}

fn postgres_service(stack: &Stack) -> ComposeService {
    let mut svc = ComposeService::new("postgres", &postgres_image(stack));
    svc.ports = vec![format!("{POSTGRES_PORT}:{POSTGRES_PORT}")];
    // TODO(hackathon): generate a password into a .env secret file instead
    svc.environment.insert("POSTGRES_USER".into(), stack.postgres.user.clone().unwrap_or_else(|| "postgres".into()));
    svc.environment.insert("POSTGRES_PASSWORD".into(), stack.postgres.password.clone().unwrap_or_else(|| "postgres".into()));
    svc.environment.insert("POSTGRES_DB".into(), API_PG_DATABASE.into());
    // Postgres 18+ images keep data in a version-specific subdirectory and
    // require the mount at /var/lib/postgresql (not .../data), enabling
    // pg_upgrade across majors. Tags <= 17 need .../data instead.
    svc.volumes = vec!["../chainstate/postgres:/var/lib/postgresql".into()];

    // Ensure the API's schema exists on EVERY boot, not just first init —
    // /docker-entrypoint-initdb.d only runs on an empty data directory.
    // Mirrors the stacks-blockchain-api test scaffold: start postgres, wait
    // until it accepts connections, create the schema, then wait on postgres.
    let user = stack.postgres.user.clone().unwrap_or_else(|| "postgres".into());
    let db = API_PG_DATABASE;
    svc.entrypoint = vec![
        "/bin/bash".into(),
        "-c".into(),
        format!(
            "docker-entrypoint.sh postgres & \
             until pg_isready -U {user}; do sleep 3; done && \
             psql -U {user} -d {db} -c 'CREATE SCHEMA IF NOT EXISTS {API_PG_SCHEMA};' || true && \
             wait"
        ),
    ];
    svc
}

/// The stacks-node Config.toml. Cross-service values (bitcoind endpoint, event
/// observers, signer auth) are derived from the same `Stack` the other configs
/// come from — matched by construction.
fn node_config_toml(stack: &Stack) -> String {
    let mut out = String::new();

    let (burn_mode, chain) = match stack.network {
        Network::Mainnet => ("mainnet", "bitcoin"),
        Network::Testnet => ("krypton", "bitcoin"),
        Network::Mocknet => ("mocknet", "bitcoin"),
    };

    out.push_str("[node]\n");
    out.push_str("working_dir = \"/stacks-blockchain\"\n");
    out.push_str(&format!("rpc_bind = \"0.0.0.0:{NODE_RPC_PORT}\"\n"));
    out.push_str(&format!("p2p_bind = \"0.0.0.0:{NODE_P2P_PORT}\"\n"));
    if stack.stacks_signer.mode != ServiceMode::Disabled {
        out.push_str("stacker = true\n");
    } else {
        out.push_str("miner = false\nstacker = false\n");
    }
    out.push('\n');

    out.push_str("[connection_options]\n");
    out.push_str(&format!("auth_token = \"{}\"\n", node_auth_token(stack)));
    out.push_str("private_neighbors = false\n\n");

    out.push_str("[burnchain]\n");
    out.push_str(&format!("mode = \"{burn_mode}\"\nchain = \"{chain}\"\n"));
    if let Some(host) = bitcoind_host(stack) {
        let rpc = stack.bitcoind.rpc_port.unwrap_or(bitcoind_rpc_port(stack.network));
        let p2p = stack.bitcoind.p2p_port.unwrap_or(bitcoind_p2p_port(stack.network));
        out.push_str(&format!("peer_host = \"{host}\"\n"));
        out.push_str(&format!("rpc_port = {rpc}\npeer_port = {p2p}\n"));
        out.push_str(&format!(
            "username = \"{}\"\npassword = \"{}\"\n",
            stack.bitcoind.rpc_user.as_deref().unwrap_or("stacks"),
            stack.bitcoind.rpc_password.as_deref().unwrap_or("stacks"),
        ));
    }
    out.push('\n');

    if stack.stacks_api.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[[events_observer]]\nendpoint = \"stacks-api:{API_EVENT_PORT}\"\nevents_keys = {API_EVENTS_KEYS}\ntimeout_ms = 300_000\n\n"
        ));
    } else if stack.stacks_api.mode == ServiceMode::External {
        if let (Some(host), Some(port)) = (&stack.stacks_api.event_host, stack.stacks_api.event_port) {
            out.push_str(&format!(
                "[[events_observer]]\nendpoint = \"{host}:{port}\"\nevents_keys = {API_EVENTS_KEYS}\ntimeout_ms = 300_000\n\n"
            ));
        }
    }

    if stack.stacks_signer.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[[events_observer]]\nendpoint = \"stacks-signer:{SIGNER_ENDPOINT_PORT}\"\nevents_keys = [\"stackerdb\", \"block_proposal\", \"burn_blocks\"]\n\n"
        ));
    }

    out
}

fn signer_config_toml(stack: &Stack) -> String {
    let node_host = node_rpc_host(stack).unwrap_or_default();
    format!(
        r#"node_host = "{node_host}:{rpc_port}"
endpoint = "0.0.0.0:{endpoint_port}"
auth_password = "{auth}"
network = "{network}"
db_path = "/var/lib/stacks-signer/signerdb.sqlite"
# TODO(hackathon): source the signing key from a secrets file, never this rendered config
stacks_private_key = "REPLACE_ME"
"#,
        rpc_port = node_rpc_port(stack),
        endpoint_port = SIGNER_ENDPOINT_PORT,
        auth = node_auth_token(stack),
        network = stack.network,
    )
}

/// The node's `connection_options.auth_token`, which the signer's
/// `auth_password` must match. External nodes bring their own token
/// (`[stacks-node] auth_token`); managed nodes use a tool-managed one.
// TODO(hackathon): generate per-stack random token into a gitignored secrets file.
fn node_auth_token(stack: &Stack) -> String {
    if stack.stacks_node.mode == ServiceMode::External {
        if let Some(token) = &stack.stacks_node.auth_token {
            return token.clone();
        }
    }
    "stacks-tool-dev-auth-token".into()
}

fn api_env(stack: &Stack) -> String {
    let chain_id = match stack.network {
        Network::Mainnet => "0x00000001",
        _ => "0x80000000",
    };
    let node_host = node_rpc_host(stack).unwrap_or_default();
    let pg_host = postgres_host(stack).unwrap_or_default();
    format!(
        r#"NODE_ENV=production
STACKS_CHAIN_ID={chain_id}
STACKS_BLOCKCHAIN_API_HOST=0.0.0.0
STACKS_BLOCKCHAIN_API_PORT={api_port}
STACKS_CORE_EVENT_HOST=0.0.0.0
STACKS_CORE_EVENT_PORT={event_port}
STACKS_CORE_RPC_HOST={node_host}
STACKS_CORE_RPC_PORT={node_rpc}
PG_HOST={pg_host}
PG_PORT={pg_port}
PG_USER={pg_user}
PG_PASSWORD={pg_password}
PG_DATABASE={pg_db}
PG_SCHEMA={pg_schema}
STACKS_API_STORE_RAW_EVENTS=false
TESTNET_BTC_FAUCET_ENABLED=false
TESTNET_STX_FAUCET_ENABLED=false
TESTNET_SBTC_FAUCET_ENABLED=false
"#,
        api_port = API_PORT,
        event_port = API_EVENT_PORT,
        node_rpc = node_rpc_port(stack),
        pg_port = postgres_port(stack),
        pg_schema = API_PG_SCHEMA,
        pg_user = stack.postgres.user.as_deref().unwrap_or("postgres"),
        pg_password = stack.postgres.password.as_deref().unwrap_or("postgres"),
        pg_db = API_PG_DATABASE,
    )
}

/// Config the user must apply to their *external* node so push edges
/// (events to the API, signer wiring) actually close.
fn apply_to_your_node(stack: &Stack) -> Option<String> {
    let mut out = String::from(
        "# Add these blocks to your stacks-node config, then restart it.\n\
         # Verify events are flowing afterwards with `stacks config check`.\n\n",
    );
    let mut needed = false;

    if stack.stacks_api.mode == ServiceMode::Enabled {
        // TODO(hackathon): make the advertised host configurable; the external
        // node must be able to reach the machine running this stack.
        out.push_str(&format!(
            "[[events_observer]]\nendpoint = \"<this-machine>:{API_EVENT_PORT}\"\nevents_keys = {API_EVENTS_KEYS}\n\n"
        ));
        needed = true;
    }
    if stack.stacks_signer.mode == ServiceMode::Enabled {
        out.push_str(&format!(
            "[node]\nstacker = true\n\n\
             [connection_options]\nauth_token = \"{}\"\n\n\
             [[events_observer]]\nendpoint = \"<this-machine>:{SIGNER_ENDPOINT_PORT}\"\nevents_keys = [\"stackerdb\", \"block_proposal\", \"burn_blocks\"]\n\n",
            node_auth_token(stack)
        ));
        needed = true;
    }

    needed.then_some(out)
}
